# Define the sequences
sge1_seq <- "CATACGTGCCCCAAGAATTGTTGTGCTGCATATGCGATTCTTCTCCTTCCAGTTTGAGATTCGCAGAATGCTGCTGAGAGCCATCGAGACTGGGTTCTTGCTGAGGCAGTGTTCGGGGCGAGGGGAATGCGTCCGCATGCTGCACCGGCTCCTGCAGACGTCCGTTATTGCCGTAGATAGGCGTAGCTTGCATGAAGGGATGGTTCATGTTTCTGATTGGGTCCACTGGGCTGTTGGTCATCGTCTGAGCGAGCCCTATGGCGTGGCTCGAGTTGCTCAAGTCATAGGCCGTGGAGTGCCCATTGTATCGATAATTGTAAATGTAATTGTAATGTTGTTTGTTGTTTGTTGTTGTTGGTAATTGTTGTAAAAATGAGCTCTTATACTCGAGCG"
sge1_reverse_seq <- "CGCTCGAGTATAAGAGCTCATTTTTACAACAATTACCAACAACAACAAACAACAAACAACATTACAATTACATTTACAATTATCGATACAATGGGCACTCCACGGCCTATGACTTGAGCAACTCGAGCCACGCCATAGGGCTCGCTCAGACGATGACCAACAGCCCAGTGGACCCAATCAGAAACATGAACCATCCCTTCATGCAAGCTACGCCTATCTACGGCAATAACGGACGTCTGCAGGAGCCGGTGCAGCATGCGGACGCATTCCCCTCGCCCCGAACACTGCCTCAGCAAGAACCCAGTCTCGATGGCTCTCAGCAGCATTCTGCGAATCTCAAACTGGAAGGAGAAGAATCGCATATGCAGCACAACAATTCTTGGGGCACGTATG"

# Function to generate 21-nt siRNAs
generate_sirnas <- function(sequence) {
  siRNAs <- sapply(1:(nchar(sequence) - 20), function(i) substr(sequence, i, i + 20))
  return(siRNAs)
}

# Generate siRNAs for both sequences
sge1_sirnas <- generate_sirnas(sge1_seq)
sge1_reverse_sirnas <- generate_sirnas(sge1_reverse_seq)

# Write the siRNAs to FASTA files
write_fasta <- function(siRNAs, file_name) {
  con <- file(file_name, "w")
  for (i in seq_along(siRNAs)) {
    cat(sprintf(">siRNA_%d\n%s\n", i, siRNAs[i]), file = con)
  }
  close(con)
}

# Save the siRNAs to FASTA files
write_fasta(sge1_sirnas, "sge1_sirnas.fasta")
write_fasta(sge1_reverse_sirnas, "sge1_reverse_sirnas.fasta")

cat("FASTA files generated successfully!\n")
